# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fixed-rate bullet loan amortization schedule calculation function.
NULL

fixed_bullet_ <- function(amount, interest_rate, start_date, end_date = NULL, n_payments = NULL, frequency = 12L, optional_parameters = NULL, truncate_month_day = TRUE) {
    .Call(`_amortr_fixed_bullet_`, amount, interest_rate, start_date, end_date, n_payments, frequency, optional_parameters, truncate_month_day)
}

fixed_french_ <- function(amount, interest_rate, start_date, end_date = NULL, n_payments = NULL, frequency = 12L, optional_parameters = NULL, truncate_month_day = TRUE) {
    .Call(`_amortr_fixed_french_`, amount, interest_rate, start_date, end_date, n_payments, frequency, optional_parameters, truncate_month_day)
}

#' Fixed-rate german loan amortization schedule calculation function.
NULL

fixed_german_ <- function(amount, interest_rate, start_date, end_date = NULL, n_payments = NULL, frequency = 12L, optional_parameters = NULL, truncate_month_day = TRUE) {
    .Call(`_amortr_fixed_german_`, amount, interest_rate, start_date, end_date, n_payments, frequency, optional_parameters, truncate_month_day)
}

